default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
 
 
development:
  <<: *default
  database: Clinicbook_development
  password: postgres
 
 
test:
  <<: *default
  database: Clinicbook_test
  password: postgres
 
 
production:
  <<: *default
  database: Clinicbook_production
  username: Clinicbook
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>